"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import Link from "next/link";
import { Check, ChevronLeft, Clock3, Copy, FileText, Highlighter, LayoutDashboard, MessageSquareText, Search, Send, Share2, Sparkles, Users, X, Trash2, RotateCcw } from "lucide-react";
import { seedMeetings } from "@/lib/meetings";
import { Meeting, Segment } from "@/lib/types";
import type { MeetingAnswer } from "@/lib/ai";
type SearchResult = { meeting: Meeting; segment?: Segment; kind: "Meeting" | "Transcript" | "Decision" | "Action item"; excerpt: string };

export type RelayView = "overview" | "meetings" | "search" | "actions";
export default function Home() { return <RelayApp initialView="overview"/>; }
export function RelayApp({ initialView }: { initialView: RelayView }) {
 const [meetings, setMeetings] = useState<Meeting[]>(() => { if (typeof window === "undefined") return seedMeetings; try { return JSON.parse(localStorage.getItem("relay-meetings") ?? "null") ?? seedMeetings; } catch { return seedMeetings; } });
 const [selectedId, setSelectedId] = useState<string | null>(null), [query, setQuery] = useState(""), [selectedSegment, setSelectedSegment] = useState<string | null>(null), [ask, setAsk] = useState(""), [answer, setAnswer] = useState<MeetingAnswer | null>(null), [askError, setAskError] = useState(""), [asking, setAsking] = useState(false), [share, setShare] = useState(false), [shareClip, setShareClip] = useState(false), [notice, setNotice] = useState("");
 const persist = (next: Meeting[]) => { setMeetings(next); localStorage.setItem("relay-meetings", JSON.stringify(next)); };
 const meeting = meetings.find(m=>m.id===selectedId);
 const results = useMemo<SearchResult[]>(()=> { const q=query.trim().toLowerCase(); if (!q) return []; return meetings.flatMap(m=>[
  ...(m.title.toLowerCase().includes(q)||m.summary.toLowerCase().includes(q)?[{meeting:m,kind:"Meeting" as const,excerpt:m.summary}]:[]),
  ...m.segments.filter(s=>s.text.toLowerCase().includes(q)||s.speaker.toLowerCase().includes(q)).map(segment=>({meeting:m,segment,kind:"Transcript" as const,excerpt:segment.text})),
  ...m.decisions.filter(d=>`${d.title} ${d.detail}`.toLowerCase().includes(q)).map(d=>({meeting:m,segment:m.segments[3],kind:"Decision" as const,excerpt:d.title})),
  ...m.actions.filter(a=>`${a.title} ${a.assignee}`.toLowerCase().includes(q)).map(a=>({meeting:m,segment:m.segments[3],kind:"Action item" as const,excerpt:`${a.title} · ${a.assignee}`}))
 ]); },[meetings,query]);
 const openResult=(r:SearchResult)=>{setSelectedId(r.meeting.id);setSelectedSegment(r.segment?.id??null);setQuery("");};
 const saveHighlight=(s:Segment)=>{if(!meeting||meeting.highlights.some(h=>h.segmentId===s.id)){setNotice("This moment is already highlighted");return;} persist(meetings.map(m=>m.id===meeting.id?{...m,highlights:[...m.highlights,{id:crypto.randomUUID(),meetingId:meeting.id,segmentId:s.id,timestamp:s.time,speaker:s.speaker,text:s.text,createdAt:new Date().toISOString()}]}:m));setNotice("Highlight saved");};
 const askMeeting=async(question=ask)=>{if(!meeting)return; if(question.trim().length<3){setAskError("Ask a question with at least 3 characters.");return;}setAsk(question);setAsking(true);setAskError("");setAnswer(null);try{const res=await fetch("/api/ask",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({meetingId:meeting.id,question})});const data=await res.json();if(!res.ok)throw new Error(data.error||"Unable to answer right now.");setAnswer(data);if(data.notice)setNotice(data.notice);}catch(e){setAskError(e instanceof Error?e.message:"Unable to answer right now.");}finally{setAsking(false);}};
 if (meeting) return <main className="shell"><Sidebar active="meetings"/><section className="workspace">
  <header className="topbar"><button className="back" onClick={()=>setSelectedId(null)}><ChevronLeft size={18}/> Meetings</button><div className="header-actions"><span className="status"><i/> {meeting.status === "completed" ? "Processed" : "Scheduled"}</span><button className="button" onClick={()=>setShare(true)}><Share2 size={16}/> Share</button></div></header>
  <div className="meeting-head"><div><p className="eyebrow">{meeting.category}</p><h1>{meeting.title}</h1><div className="meta"><span><Clock3 size={15}/>{meeting.time}</span><span>{meeting.duration}</span><span><Users size={15}/>{meeting.participants.length} attendees</span></div></div><div className="avatars">{meeting.participants.map(p=><span title={p.name} className={`avatar ${p.tone}`} key={p.name}>{p.initials}</span>)}</div></div>
  <div className="workspace-grid"><div className="content"><section className="summary-card"><div className="section-title"><span className="icon-block"><Sparkles size={17}/></span><div><p className="eyebrow">MEETING BRIEF</p><h2>What happened</h2></div></div><p>{meeting.summary}</p><div className="decision-grid">{meeting.decisions.map((d,i)=><article key={d.id}><span>0{i+1}</span><h3>{d.title}</h3><p>{d.detail}</p></article>)}</div></section>
    <section className="panel transcript"><div className="panel-heading"><div><p className="eyebrow">CONVERSATION</p><h2>Transcript</h2></div><span className="muted">Choose a moment to save or ask about it</span></div>{meeting.segments.map(s=>{const highlighted=meeting.highlights.some(h=>h.segmentId===s.id);return <button key={s.id} id={s.id} className={`segment ${selectedSegment===s.id?"selected":""} ${highlighted?"highlighted":""}`} onClick={()=>setSelectedSegment(s.id)}><time>{s.time}</time><div><b>{s.speaker}</b><p>{s.text}</p>{highlighted&&<span className="saved-tag"><Highlighter size={12}/> Highlighted</span>}{selectedSegment===s.id&&<span className="segment-actions"><em onClick={e=>{e.stopPropagation();saveHighlight(s);}}><Highlighter size={14}/> Highlight</em><em onClick={e=>{e.stopPropagation();setAsk(`What is important about this moment: “${s.text}”`);document.getElementById("ask")?.scrollIntoView({behavior:"smooth"});}}><MessageSquareText size={14}/> Ask AI</em></span>}</div></button>})}</section></div>
   <aside className="right-rail"><section className="panel compact"><div className="panel-heading"><h2>Action items</h2><span className="count">{meeting.actions.filter(a=>!a.done).length}</span></div>{meeting.actions.map(a=><label className={`action ${a.done?"done":""}`} key={a.id}><input type="checkbox" checked={a.done} onChange={()=>persist(meetings.map(m=>m.id===meeting.id?{...m,actions:m.actions.map(x=>x.id===a.id?{...x,done:!x.done}:x)}:m))}/><span><b>{a.title}</b><small>{a.assignee} · {a.due}</small></span></label>)}</section>
   <section className="panel compact highlights"><div className="panel-heading"><h2>Highlights</h2><span className="count">{meeting.highlights.length}</span></div>{meeting.highlights.length?meeting.highlights.map(h=><div className="highlight-item" key={h.id}><button onClick={()=>{setSelectedSegment(h.segmentId);document.getElementById(h.segmentId)?.scrollIntoView({behavior:"smooth",block:"center"});}}><time>{h.timestamp}</time><b>{h.speaker}</b><p>{h.text}</p>{h.note&&<small>“{h.note}”</small>}</button><button className="remove" aria-label="Remove highlight" onClick={()=>{persist(meetings.map(m=>m.id===meeting.id?{...m,highlights:m.highlights.filter(x=>x.id!==h.id)}:m));setNotice("Highlight removed");}}><Trash2 size={14}/></button></div>):<div className="empty"><Highlighter size={19}/><p>Select a transcript moment to save what matters.</p></div>}</section>
   <section id="ask" className="ask-card"><div className="section-title"><span className="icon-block"><Sparkles size={16}/></span><h2>Ask this meeting</h2></div><p>Answers are grounded in this meeting’s transcript.</p><div className="suggestions">{["What were the key decisions?","What action items were assigned?","What risks were discussed?","What did we decide about onboarding?"].map(q=><button key={q} onClick={()=>askMeeting(q)}>{q}</button>)}</div><div className="ask-input"><input value={ask} maxLength={500} onChange={e=>setAsk(e.target.value)} onKeyDown={e=>e.key==="Enter"&&askMeeting()} placeholder="Ask about this meeting..."/><button aria-label="Ask" disabled={asking} onClick={()=>askMeeting()}>{asking?<span className="spinner"/>:<Send size={16}/>}</button></div>{askError&&<p className="form-error">{askError}</p>}{answer&&<div className="answer"><div><small>{answer.mode}</small><button aria-label="Clear answer" onClick={()=>{setAnswer(null);setAsk("");}}><RotateCcw size={13}/> Clear</button></div><p>{answer.answer}</p>{answer.sources.length?answer.sources.map(s=><button key={s.id} onClick={()=>{setSelectedSegment(s.id);document.getElementById(s.id)?.scrollIntoView({behavior:"smooth",block:"center"});}}><span>{s.time} · {s.speaker}</span> {s.text}</button>):<small>No specific source moment was identified.</small>}</div>}</section></aside></div>
  {share&&<ShareDialog meeting={meeting} selectedSegment={meeting.segments.find(s=>s.id===selectedSegment)} shareClip={shareClip} setShareClip={setShareClip} close={()=>setShare(false)} notify={setNotice}/>} {notice&&<div className="toast"><Check size={16}/>{notice}</div>}
 </section></main>;
 if (initialView === "meetings") return <main className="shell"><Sidebar active="meetings"/><section className="dashboard"><header className="dash-head"><div><p className="eyebrow">YOUR CONVERSATIONS</p><div className="page-title-row"><Link className="page-back" href="/" aria-label="Back to overview"><ChevronLeft size={18}/></Link><h1>Meetings</h1></div><p className="sub">Review the context, decisions, and follow-through from every conversation.</p></div><SearchBox query={query} setQuery={setQuery} results={results} open={openResult}/></header><section className="panel meetings-panel route-panel"><div className="panel-heading"><h2>All meetings</h2><span className="count">{meetings.length}</span></div><MeetingRows meetings={meetings} open={id=>setSelectedId(id)}/></section></section></main>;
 if (initialView === "search") return <main className="shell"><Sidebar active="search"/><section className="dashboard"><header className="dash-head"><div><p className="eyebrow">FIND CONTEXT</p><div className="page-title-row"><Link className="page-back" href="/" aria-label="Back to overview"><ChevronLeft size={18}/></Link><h1>Search</h1></div><p className="sub">Search meetings, transcript moments, decisions, and action items.</p></div></header><section className="panel route-panel search-page"><SearchBox query={query} setQuery={setQuery} results={results} open={openResult}/><p className="search-help">Start with a topic like “onboarding”, a person, or an action item.</p></section></section></main>;
 if (initialView === "actions") { const actions=meetings.flatMap(m=>m.actions.map(action=>({meeting:m,action}))); return <main className="shell"><Sidebar active="actions"/><section className="dashboard"><header className="dash-head"><div><p className="eyebrow">OWNERSHIP</p><div className="page-title-row"><Link className="page-back" href="/" aria-label="Back to overview"><ChevronLeft size={18}/></Link><h1>Action items</h1></div><p className="sub">Keep every meeting commitment visible and moving.</p></div></header><section className="panel route-panel action-list"><div className="panel-heading"><h2>Open action items</h2><span className="count">{actions.filter(x=>!x.action.done).length}</span></div>{actions.map(({meeting:m,action:a})=><label className={`action route-action ${a.done?"done":""}`} key={a.id}><input type="checkbox" checked={a.done} onChange={()=>persist(meetings.map(x=>x.id===m.id?{...x,actions:x.actions.map(y=>y.id===a.id?{...y,done:!y.done}:y)}:x))}/><span><b>{a.title}</b><small>{a.assignee} · {a.due} · <button onClick={()=>setSelectedId(m.id)}>{m.title}</button></small></span></label>)}</section></section></main>; }
 return <main className="shell"><Sidebar active="overview"/><section className="dashboard"><header className="dash-head"><div><p className="eyebrow">THURSDAY, OCTOBER 2</p><h1>Good morning, Paras.</h1><p className="sub">Here’s the signal from your team’s conversations.</p></div><SearchBox query={query} setQuery={setQuery} results={results} open={openResult}/></header><div className="stat-row"><Stat label="Meetings this week" value="12" change="↑ 20%"/><Stat label="Open action items" value={String(meetings.flatMap(m=>m.actions).filter(a=>!a.done).length)} change="Across 6 meetings"/><Stat label="Time recovered" value="4.5h" change="This week"/></div><div className="dash-grid"><section className="panel meetings-panel"><div className="panel-heading"><div><p className="eyebrow">RECENT CONVERSATIONS</p><h2>Meetings</h2></div><Link className="text-button" href="/meetings">View all</Link></div><MeetingRows meetings={meetings.filter(m=>m.status==="completed").slice(0,6)} open={id=>setSelectedId(id)}/></section><aside><section className="panel upcoming"><div className="panel-heading"><div><p className="eyebrow">NEXT UP</p><h2>Upcoming</h2></div></div>{meetings.filter(m=>m.status==="upcoming").map(m=><button key={m.id} onClick={()=>setSelectedId(m.id)}><span className="date-tile">{m.date==="Tomorrow"?"03":"04"}<small>OCT</small></span><div><b>{m.title}</b><p>{m.time}</p></div></button>)}</section><section className="focus-card"><span className="icon-block"><Check size={16}/></span><p className="eyebrow">YOUR FOCUS</p><h2>{meetings.flatMap(m=>m.actions).filter(a=>!a.done).length} actions need attention</h2><Link href="/action-items">Review action items <ChevronLeft size={15}/></Link></section></aside></div></section></main>;
}
function SearchBox({query,setQuery,results,open}:{query:string;setQuery:(x:string)=>void;results:SearchResult[];open:(r:SearchResult)=>void}){return <div className="search-wrap"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search meetings, decisions, actions..."/>{query&&<button className="clear-search" aria-label="Clear search" onClick={()=>setQuery("")}><X size={14}/></button>}{query&&<div className="search-results">{results.length?results.slice(0,8).map((r,i)=><button key={i} onClick={()=>open(r)}><small>{r.kind}{r.segment&&` · ${r.segment.time} · ${r.segment.speaker}`}</small><b>{r.meeting.title}</b><span>{r.excerpt}</span></button>):<div className="empty"><Search size={18}/><p>No results for “{query}”. Try a topic, person, or action.</p></div>}</div>}</div>}
function ShareDialog({meeting,selectedSegment,shareClip,setShareClip,close,notify}:{meeting:Meeting;selectedSegment?:Segment;shareClip:boolean;setShareClip:(x:boolean)=>void;close:()=>void;notify:(x:string)=>void}){const canClip=Boolean(selectedSegment);const path=`${typeof window!=="undefined"?window.location.origin:""}/share/${meeting.id}${shareClip&&selectedSegment?`?clip=${selectedSegment.id}`:""}`;return <div className="modal-backdrop"><div className="modal"><button className="close" onClick={close}><X/></button><span className="icon-block"><Share2 size={18}/></span><p className="eyebrow">SHARE LINK</p><h2>Share this meeting</h2><p>This public link opens a focused, read-only meeting view. It does not require sign-in.</p><div className="share-options"><label><input type="radio" checked={!shareClip} onChange={()=>setShareClip(false)}/> Entire meeting</label><label className={!canClip?"disabled":""}><input type="radio" disabled={!canClip} checked={shareClip} onChange={()=>setShareClip(true)}/> Selected moment {canClip?`(${selectedSegment?.time})`:"— select a transcript moment first"}</label></div><div className="linkbox"><span>{path}</span><button onClick={async()=>{try{await navigator.clipboard.writeText(path);notify("Share link copied");close();}catch{notify("Copy failed — select the link manually.");}}}><Copy size={15}/> Copy link</button></div><p className="share-status"><i/> Shared publicly · Read-only</p></div></div>}
function MeetingRows({meetings,open}:{meetings:Meeting[];open:(id:string)=>void}){return <>{meetings.map(m=><button className="meeting-row" key={m.id} onClick={()=>open(m.id)}><span className="meeting-icon"><FileText size={18}/></span><div><b>{m.title}</b><p>{m.date} · {m.duration} · {m.participants.map(p=>p.initials).join(", ")}</p></div><span className="row-summary">{m.summary}</span><ChevronLeft className="row-arrow" size={17}/></button>)}</>}
function Sidebar({active}:{active:RelayView}){const [profileOpen,setProfileOpen]=useState(false);const profileRef=useRef<HTMLDivElement>(null);useEffect(()=>{const close=(event:MouseEvent)=>{if(!profileRef.current?.contains(event.target as Node))setProfileOpen(false)};const escape=(event:KeyboardEvent)=>{if(event.key==="Escape")setProfileOpen(false)};document.addEventListener("mousedown",close);document.addEventListener("keydown",escape);return()=>{document.removeEventListener("mousedown",close);document.removeEventListener("keydown",escape)}},[]);return <aside className="sidebar"><div className="brand"><span>R</span> relay</div><nav><Link className={active==="overview"?"active":""} href="/"><LayoutDashboard size={18}/> Overview</Link><Link className={active==="meetings"?"active":""} href="/meetings"><MessageSquareText size={18}/> Meetings</Link><Link className={active==="search"?"active":""} href="/search"><Search size={18}/> Search</Link><Link className={active==="actions"?"active":""} href="/action-items"><Check size={18}/> Action items <i>8</i></Link></nav><div className="sidebar-bottom" ref={profileRef}><button className="profile profile-trigger" type="button" aria-expanded={profileOpen} aria-haspopup="dialog" aria-controls="profile-popover" onClick={()=>setProfileOpen(open=>!open)}><span className="avatar violet">PK</span><span><b>Paras Kumar</b><small>Acme Inc.</small></span></button>{profileOpen&&<div id="profile-popover" className="profile-popover" role="dialog" aria-label="Profile"><span className="avatar violet">PK</span><div><b>Paras Kumar</b><small>Acme Inc.</small></div></div>}</div></aside>}
function Stat({label,value,change}:{label:string;value:string;change:string}){return <section className="stat"><p>{label}</p><h2>{value}</h2><span>{change}</span></section>}
