"use client";
import { useMemo, useState } from "react";
import { Check, ChevronLeft, Clock3, Copy, FileText, Highlighter, LayoutDashboard, MessageSquareText, Search, Send, Share2, Sparkles, Users, X } from "lucide-react";
import { seedMeetings } from "@/lib/meetings";
import { answerMeetingQuestion } from "@/lib/ai";
import { Meeting, Segment } from "@/lib/types";

const initials = (n: string) => n.split(" ").map(x => x[0]).join("");
export default function Home() {
 const [meetings, setMeetings] = useState<Meeting[]>(() => { if (typeof window === "undefined") return seedMeetings; try { return JSON.parse(localStorage.getItem("relay-meetings") ?? "null") ?? seedMeetings; } catch { return seedMeetings; } }), [selectedId, setSelectedId] = useState<string | null>(null), [query, setQuery] = useState(""), [selectedSegment, setSelectedSegment] = useState<string | null>(null), [ask, setAsk] = useState(""), [answer, setAnswer] = useState<ReturnType<typeof answerMeetingQuestion> | null>(null), [share, setShare] = useState(false), [notice, setNotice] = useState("");
 const persist = (next: Meeting[]) => { setMeetings(next); localStorage.setItem("relay-meetings", JSON.stringify(next)); };
 const meeting = meetings.find(m=>m.id===selectedId);
 const results = useMemo(()=> query.trim() ? meetings.flatMap(m => [{ m, segment: undefined as Segment|undefined, match: m.title.toLowerCase().includes(query.toLowerCase()) || m.summary.toLowerCase().includes(query.toLowerCase()) }].filter(x=>x.match).concat(m.segments.filter(s=>s.text.toLowerCase().includes(query.toLowerCase())).map(segment=>({m,segment,match:true})))) : [], [query, meetings]);
 const openResult=(m:Meeting,s?:Segment)=>{setSelectedId(m.id);setSelectedSegment(s?.id??null);setQuery("");};
 if (meeting) return <main className="shell"><Sidebar active="Meetings" onHome={()=>setSelectedId(null)} /><section className="workspace">
  <header className="topbar"><button className="back" onClick={()=>setSelectedId(null)}><ChevronLeft size={18}/> Meetings</button><div className="header-actions"><span className="status"><i/> {meeting.status === "completed" ? "Processed" : "Scheduled"}</span><button className="button ghost" onClick={()=>setShare(true)}><Share2 size={16}/> Share</button></div></header>
  <div className="meeting-head"><div><p className="eyebrow">{meeting.category}</p><h1>{meeting.title}</h1><div className="meta"><span><Clock3 size={15}/>{meeting.time}</span><span>{meeting.duration}</span><span><Users size={15}/>{meeting.participants.length} attendees</span></div></div><div className="avatars">{meeting.participants.map(p=><span title={p.name} className={`avatar ${p.tone}`} key={p.name}>{p.initials}</span>)}</div></div>
  <div className="workspace-grid"><div className="content">
    <section className="summary-card"><div className="section-title"><span className="icon-block"><Sparkles size={17}/></span><div><p className="eyebrow">AI BRIEF</p><h2>What happened</h2></div></div><p>{meeting.summary}</p><div className="decision-grid">{meeting.decisions.map((d,i)=><article key={d.id}><span>0{i+1}</span><h3>{d.title}</h3><p>{d.detail}</p></article>)}</div></section>
    <section className="panel transcript"><div className="panel-heading"><div><p className="eyebrow">CONVERSATION</p><h2>Transcript</h2></div><span className="muted">Click a moment to focus it</span></div>{meeting.segments.map(s=><button key={s.id} className={`segment ${selectedSegment===s.id?"selected":""}`} onClick={()=>setSelectedSegment(s.id)}><time>{s.time}</time><div><b>{s.speaker}</b><p>{s.text}</p>{selectedSegment===s.id&&<span className="segment-actions"><em onClick={(e)=>{e.stopPropagation(); const next=meetings.map(m=>m.id===meeting.id?{...m,highlights:[...m.highlights,{id:crypto.randomUUID(),segmentId:s.id}]}:m);persist(next);setNotice("Highlight saved");}}><Highlighter size={14}/> Highlight</em><em onClick={(e)=>{e.stopPropagation();setAsk(`What is important about this moment: “${s.text}”`);document.getElementById("ask")?.scrollIntoView({behavior:"smooth"});}}><MessageSquareText size={14}/> Ask AI</em></span>}</div></button>)}</section>
  </div><aside className="right-rail">
   <section className="panel compact"><div className="panel-heading"><h2>Action items</h2><span className="count">{meeting.actions.filter(a=>!a.done).length}</span></div>{meeting.actions.map(a=><label className={`action ${a.done?"done":""}`} key={a.id}><input type="checkbox" checked={a.done} onChange={()=>persist(meetings.map(m=>m.id===meeting.id?{...m,actions:m.actions.map(x=>x.id===a.id?{...x,done:!x.done}:x)}:m))}/><span><b>{a.title}</b><small>{a.assignee} · {a.due}</small></span></label>)}</section>
   <section className="panel compact highlights"><div className="panel-heading"><h2>Highlights</h2><span className="count">{meeting.highlights.length}</span></div>{meeting.highlights.length?meeting.highlights.map(h=>{const s=meeting.segments.find(x=>x.id===h.segmentId)!;return <button key={h.id} onClick={()=>setSelectedSegment(s.id)}><time>{s.time}</time><b>{s.speaker}</b><p>{s.text}</p></button>}):<div className="empty"><Highlighter size={19}/><p>Your saved moments will appear here.</p></div>}</section>
   <section id="ask" className="ask-card"><div className="section-title"><span className="icon-block"><Sparkles size={16}/></span><h2>Ask Relay</h2></div><p>Get a grounded answer from this meeting.</p><div className="ask-input"><input value={ask} onChange={e=>setAsk(e.target.value)} placeholder="What did we decide?"/><button aria-label="Ask" onClick={()=>ask.trim()&&setAnswer(answerMeetingQuestion(meeting,ask))}><Send size={16}/></button></div>{answer&&<div className="answer"><small>{answer.mode}</small><p>{answer.answer}</p>{answer.sources.map(s=><button key={s.id} onClick={()=>setSelectedSegment(s.id)}><span>{s.time}</span> {s.text}</button>)}</div>}</section>
  </aside></div>
  {share&&<div className="modal-backdrop"><div className="modal"><button className="close" onClick={()=>setShare(false)}><X/></button><span className="icon-block"><Share2 size={18}/></span><h2>Share this meeting</h2><p>Anyone with the link can view the summary, decisions, and selected moments.</p><div className="linkbox">relay.so/s/{meeting.id}-brief <button onClick={()=>{navigator.clipboard.writeText(`https://relay.so/s/${meeting.id}-brief`);setNotice("Share link copied");setShare(false)}}><Copy size={15}/> Copy link</button></div><label className="share-setting"><input type="checkbox" defaultChecked/> Allow viewers to see transcript</label></div></div>}{notice&&<div className="toast"><Check size={16}/>{notice}</div>}
 </section></main>;
 return <main className="shell"><Sidebar active="Overview" onHome={()=>{}}/><section className="dashboard"><header className="dash-head"><div><p className="eyebrow">THURSDAY, OCTOBER 2</p><h1>Good morning, Paras.</h1><p className="sub">Here’s the signal from your team’s conversations.</p></div><div className="search-wrap"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search meetings and transcripts..."/>{query&&<div className="search-results">{results.length?results.map((r,i)=><button key={i} onClick={()=>openResult(r.m,r.segment)}><b>{r.m.title}</b><span>{r.segment?`${r.segment.time} · ${r.segment.text}`:r.m.summary}</span></button>):<p>No moments found for “{query}”</p>}</div>}</div></header>
 <div className="stat-row"><Stat label="Meetings this week" value="12" change="↑ 20%"/><Stat label="Open action items" value={String(meetings.flatMap(m=>m.actions).filter(a=>!a.done).length)} change="Across 6 meetings"/><Stat label="Time recovered" value="4.5h" change="This week"/></div>
 <div className="dash-grid"><section className="panel meetings-panel"><div className="panel-heading"><div><p className="eyebrow">RECENT CONVERSATIONS</p><h2>Meetings</h2></div><button className="text-button">View all</button></div>{meetings.filter(m=>m.status==="completed").slice(0,6).map(m=><button className="meeting-row" key={m.id} onClick={()=>setSelectedId(m.id)}><span className="meeting-icon"><FileText size={18}/></span><div><b>{m.title}</b><p>{m.date} · {m.duration} · {m.participants.map(p=>p.initials).join(", ")}</p></div><span className="row-summary">{m.summary}</span><ChevronLeft className="row-arrow" size={17}/></button>)}</section><aside><section className="panel upcoming"><div className="panel-heading"><div><p className="eyebrow">NEXT UP</p><h2>Upcoming</h2></div></div>{meetings.filter(m=>m.status==="upcoming").map(m=><button key={m.id} onClick={()=>setSelectedId(m.id)}><span className="date-tile">{m.date==="Tomorrow"?"03":"04"}<small>OCT</small></span><div><b>{m.title}</b><p>{m.time}</p></div></button>)}</section><section className="focus-card"><span className="icon-block"><Check size={16}/></span><p className="eyebrow">YOUR FOCUS</p><h2>{meetings.flatMap(m=>m.actions).filter(a=>!a.done).length} actions need attention</h2><button onClick={()=>setSelectedId("product")}>Review action items <ChevronLeft size={15}/></button></section></aside></div></section></main>;
}
function Sidebar({active,onHome}:{active:string;onHome:()=>void}){return <aside className="sidebar"><div className="brand"><span>R</span> relay</div><nav><button className={active==="Overview"?"active":""} onClick={onHome}><LayoutDashboard size={18}/> Overview</button><button className={active==="Meetings"?"active":""}><MessageSquareText size={18}/> Meetings</button><button><Check size={18}/> Action items <i>8</i></button></nav><div className="sidebar-bottom"><div className="profile"><span className="avatar violet">PK</span><div><b>Paras Kumar</b><small>Acme Inc.</small></div></div></div></aside>}
function Stat({label,value,change}:{label:string;value:string;change:string}){return <section className="stat"><p>{label}</p><h2>{value}</h2><span>{change}</span></section>}
